server:
  port: 8081


frontend:
  base-url: ${FRONT_END_DEV_URL}

spring:
  config:
    import: env.properties

  datasource:
    url: jdbc:postgresql://localhost/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update


  security:
    jwt:
      secret-key: ${SECRET}
      expiration-time: 300000
      refresh-token:
        expiration: 900000

