server:
  port: 8081


frontend:
  base-url: ${FRONT_END_URL} # change in production

backend:
  base-url: ${BACK_END_URL} # change in production

spring:
  config:
    import: env.properties

  datasource:
    url: jdbc:postgresql://localhost/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_EMAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  security:
    jwt:
      secret-key: ${SECRET}
      expiration-time: 300000
      refresh-token:
        expiration: 900000
      verification-token:
        expiration: 180000
